import "./globals.css";
import { Montserrat } from "next/font/google";
import type { Metadata } from "next";
import GlobalProvider from "@/components/providers/global-provider";
import { Navbar } from "@/components/index";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Library Managment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat.variable} bg-neutral-50 text-black antialiased dark:bg-neutral-950 dark:text-white`}
      >
        <GlobalProvider>
          <Navbar />
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
